spring.application.name=kanban-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/kanban
spring.datasource.username=kanban
spring.datasource.password=kanban

spring.jpa.hibernate.ddl-auto=update
